name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: List Files
        run: ls -R
      - name: Compile
        run: |
          curl -L -o api.jar https://repo.papermc.io/repository/maven-public/io/papermc/paper/paper-api/1.21.1-R0.1-SNAPSHOT/paper-api-1.21.1-R0.1-20241022.064544-16.jar
          javac -cp api.jar CakeGuard.java
          jar cvf CakeGuard.jar plugin.yml *.class
      - uses: actions/upload-artifact@v4
        with:
          name: CakeGuard-JAR
          path: CakeGuard.jar
