name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Compile
        run: |
          curl -L -o api.jar https://repo.papermc.io/repository/maven-public/io/papermc/paper/paper-api/1.21.1-R0.1-SNAPSHOT/paper-api-1.21.1-R0.1-20241022.064544-16.jar
          mkdir -p me/yarik/cakeguard
          cp CakeGuard.java me/yarik/cakeguard/
          javac -cp api.jar me/yarik/cakeguard/CakeGuard.java
          jar cvf CakeGuard.jar plugin.yml me/yarik/cakeguard/*.class
      - uses: actions/upload-artifact@v4
        with:
          name: MyPluginFile
          path: CakeGuard.jar
